package domain;
// Generated Jun 3, 2022 7:32:24 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Duan generated by hbm2java
 */
public class Duan  implements java.io.Serializable {


     private Integer mada;
     private String tenda;
     private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

    public Duan() {
    }

	
    public Duan(String tenda) {
        this.tenda = tenda;
    }
    public Duan(String tenda, Set<Nhanvien> nhanviens) {
       this.tenda = tenda;
       this.nhanviens = nhanviens;
    }
   
    public Integer getMada() {
        return this.mada;
    }
    
    public void setMada(Integer mada) {
        this.mada = mada;
    }
    public String getTenda() {
        return this.tenda;
    }
    
    public void setTenda(String tenda) {
        this.tenda = tenda;
    }
    public Set<Nhanvien> getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set<Nhanvien> nhanviens) {
        this.nhanviens = nhanviens;
    }

    @Override
    public String toString() {
        return mada+" - "+tenda;
    }
    



}


