package domain;
// Generated Jun 3, 2022 7:32:24 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private String manv;
     private Duan duan;
     private String tennv;
     private Date ngaysinh;

    public Nhanvien() {
    }

    public Nhanvien(String manv, Duan duan, String tennv, Date ngaysinh) {
       this.manv = manv;
       this.duan = duan;
       this.tennv = tennv;
       this.ngaysinh = ngaysinh;
    }
   
    public String getManv() {
        return this.manv;
    }
    
    public void setManv(String manv) {
        this.manv = manv;
    }
    public Duan getDuan() {
        return this.duan;
    }
    
    public void setDuan(Duan duan) {
        this.duan = duan;
    }
    public String getTennv() {
        return this.tennv;
    }
    
    public void setTennv(String tennv) {
        this.tennv = tennv;
    }
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }




}


